version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgres://postgres:iqF7IxfouW0Hskx0wL6gj8lp3R7dJiqXIkAViqGt2LZMrlypC6OkDeSlmxM5IfoP@twkw00kcwco0skoss80000c4:5432/postgres
      - DB_HOST=twkw00kcwco0skoss80000c4
      - DB_USER=postgres
      - DB_PASS=iqF7IxfouW0Hskx0wL6gj8lp3R7dJiqXIkAViqGt2LZMrlypC6OkDeSlmxM5IfoP
      - DB_NAME=postgres
      - DB_PORT=5432
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - REDIS_URI=redis://${REDIS_HOST:-redis}:6379
      - FRONTEND_URL=https://ticket.ebnez.com.br
      - NODE_OPTIONS="--max-old-space-size=512"
      - BASE_URL=/backend
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/backend/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    ports:
      - "3000"
    volumes:
      - backend_data:/usr/src/app/public
      - backend_private:/usr/src/app/private
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=https://ticket.ebnez.com.br/backend
      - REACT_APP_TITLE=${APP_TITLE:-Ticketz}
    volumes:
      - backend_data:/var/www/backend-public:ro
      - backend_private:/var/www/backend-private:ro
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

volumes:
  backend_data:
    driver: local
  backend_private:
    driver: local
