version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgres://postgres:iqF7IxfouW0Hskx0wL6gj8lp3R7dJiqXIkAViqGt2LZMrlypC6OkDeSlmxM5IfoP@twkw00kcwco0skoss80000c4:5432/postgres
      - DB_HOST=twkw00kcwco0skoss80000c4
      - DB_USER=postgres
      - DB_PASS=iqF7IxfouW0Hskx0wL6gj8lp3R7dJiqXIkAViqGt2LZMrlypC6OkDeSlmxM5IfoP
      - DB_NAME=postgres
      - DB_PORT=5432
      - JWT_SECRET=ticket
      - JWT_REFRESH_SECRET=ticket-refresh
      - REDIS_URI=redis://default:rZzhHPOIoCFkQ72GtiPFmX852eji4fjON2llkUMT4njZneILmtbnQGIAS7TIviNY@hsscggc48w4oo8c84o8ww4ck:6379/0
      - FRONTEND_URL=https://ticket.ebnez.com.br
      - NODE_OPTIONS=--max-old-space-size=384
      - BASE_URL=/backend
      - PM2_PUBLIC_KEY=${PM2_PUBLIC_KEY}
      - PM2_SECRET_KEY=${PM2_SECRET_KEY}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/backend/health"]
      interval: 30s
      timeout: 30s
      retries: 5
      start_period: 120s
    ports:
      - "3000"
    volumes:
      - backend_data:/usr/src/app/public
      - backend_private:/usr/src/app/private
    networks:
      - coolify
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 5
        window: 180s

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=https://ticket.ebnez.com.br/backend
      - REACT_APP_TITLE=${APP_TITLE:-Ticketz}
    volumes:
      - backend_data:/var/www/backend-public:ro
      - backend_private:/var/www/backend-private:ro
      - frontend_public:/var/www/public
    networks:
      - coolify
    depends_on:
      backend:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5
        window: 120s

volumes:
  backend_data:
  backend_private:
  frontend_public:

networks:
  coolify:
    external: true
