version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "31467:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:iqF7IxfouW0Hskx0wL6gj8lp3R7dJiqXIkAViqGt2LZMrlypC6OkDeSlmxM5IfoP@twkw00kcwco0skoss80000c4:5432/postgres
      - REDIS_URI=redis://default:rZzhHPOIoCFkQ72GtiPFmX852eji4fjON2llkUMT4njZneILmtbnQGIAS7TIviNY@hsscggc48w4oo8c84o8ww4ck:6379/0
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_PHONE=${ADMIN_PHONE}
      - ADMIN_DEPARTMENT=${ADMIN_DEPARTMENT}
      - ADMIN_ROLE=${ADMIN_ROLE}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_REJECT_UNAUTHORIZED=${SMTP_REJECT_UNAUTHORIZED}
      - WHATSAPP_ENABLED=${WHATSAPP_ENABLED}
      - WHATSAPP_WEBHOOK_URL=${WHATSAPP_WEBHOOK_URL}
      - WHATSAPP_API_URL=${WHATSAPP_API_URL}
      - WHATSAPP_API_TOKEN=${WHATSAPP_API_TOKEN}
      - WHATSAPP_WEBHOOK_TOKEN=${WHATSAPP_WEBHOOK_TOKEN}
      - WHATSAPP_WEBHOOK_VERIFY_TOKEN=${WHATSAPP_WEBHOOK_VERIFY_TOKEN}
      - WHATSAPP_WEBHOOK_VERIFY_MODE=${WHATSAPP_WEBHOOK_VERIFY_MODE}
      - WHATSAPP_WEBHOOK_VERIFY_SIGNATURE=${WHATSAPP_WEBHOOK_VERIFY_SIGNATURE}
      - WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_KEY=${WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_KEY}
      - WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_ALGORITHM=${WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_ALGORITHM}
      - WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_HEADER=${WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_HEADER}
      - WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_HEADER_VALUE=${WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_HEADER_VALUE}
      - UPLOAD_DIR=/usr/src/app/uploads
      - PUBLIC_DIR=/usr/src/app/public
      - PRIVATE_DIR=/usr/src/app/private
      - PORT=3000
    volumes:
      - type: bind
        source: ${MEDIA_STORAGE_PATH:-/var/lib/coolify/media_storage}
        target: /usr/src/app/uploads
      - type: bind
        source: ${MEDIA_STORAGE_PATH:-/var/lib/coolify/media_storage}
        target: /usr/src/app/public
      - type: bind
        source: ${MEDIA_STORAGE_PATH:-/var/lib/coolify/media_storage}
        target: /usr/src/app/private
      - type: bind
        source: ${MEDIA_STORAGE_PATH:-/var/lib/coolify/media_storage}
        target: /usr/src/app/logs
    networks:
      - coolify
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: /backend
        NODE_ENV: production
        DISABLE_ESLINT_PLUGIN: "true"
        GENERATE_SOURCEMAP: "false"
        CI: "false"
        NODE_OPTIONS: "--max-old-space-size=2048"
    ports:
      - "34467:8080"
    networks:
      - coolify
    deploy:
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
      restart_policy:
        condition: any
    depends_on:
      - backend
    volumes:
      - type: bind
        source: ${MEDIA_STORAGE_PATH:-/var/lib/coolify/media_storage}
        target: /usr/src/app/uploads
      - type: bind
        source: ${MEDIA_STORAGE_PATH:-/var/lib/coolify/media_storage}
        target: /usr/src/app/public

networks:
  coolify:
    external: true

volumes:
  media_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MEDIA_STORAGE_PATH:-/var/lib/coolify/media_storage}
