version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST:-postgres}
      - DB_USER=${DB_USER:-ticketz}
      - DB_PASS=${DB_PASS:-ticketz}
      - DB_NAME=${DB_NAME:-ticketz}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - REDIS_URI=redis://${REDIS_HOST:-redis}:6379
      - FRONTEND_URL=${FRONTEND_URL}
    volumes:
      - backend_data:/usr/src/app/public
      - backend_private:/usr/src/app/private
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    environment:
      - REACT_APP_BACKEND_URL=${BACKEND_URL}
      - REACT_APP_TITLE=${APP_TITLE:-Ticketz}
    volumes:
      - backend_data:/var/www/backend-public:ro
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  backend_data:
    driver: local
  backend_private:
    driver: local
