version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "31467:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=twkw00kcwco0skoss80000c4
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=iqF7IxfouW0Hskx0wL6gj8lp3R7dJiqXIkAViqGt2LZMrlypC6OkDeSlmxM5IfoP
      - REDIS_URI=redis://default:rZzhHPOIoCFkQ72GtiPFmX852eji4fjON2llkUMT4njZneILmtbnQGIAS7TIviNY@hsscggc48w4oo8c84o8ww4ck:6379/0
      - JWT_SECRET=${JWT_SECRET}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_PHONE=${ADMIN_PHONE}
      - ADMIN_DEPARTMENT=${ADMIN_DEPARTMENT}
      - ADMIN_ROLE=${ADMIN_ROLE}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
      - SMTP_FROM=${SMTP_FROM}
      - SMTP_SECURE=${SMTP_SECURE}
      - SMTP_REJECT_UNAUTHORIZED=${SMTP_REJECT_UNAUTHORIZED}
      - WHATSAPP_ENABLED=${WHATSAPP_ENABLED}
      - WHATSAPP_WEBHOOK_URL=${WHATSAPP_WEBHOOK_URL}
      - WHATSAPP_API_URL=${WHATSAPP_API_URL}
      - WHATSAPP_API_TOKEN=${WHATSAPP_API_TOKEN}
      - WHATSAPP_WEBHOOK_TOKEN=${WHATSAPP_WEBHOOK_TOKEN}
      - WHATSAPP_WEBHOOK_VERIFY_TOKEN=${WHATSAPP_WEBHOOK_VERIFY_TOKEN}
      - WHATSAPP_WEBHOOK_VERIFY_MODE=${WHATSAPP_WEBHOOK_VERIFY_MODE}
      - WHATSAPP_WEBHOOK_VERIFY_SIGNATURE=${WHATSAPP_WEBHOOK_VERIFY_SIGNATURE}
      - WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_KEY=${WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_KEY}
      - WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_ALGORITHM=${WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_ALGORITHM}
      - WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_HEADER=${WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_HEADER}
      - WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_HEADER_VALUE=${WHATSAPP_WEBHOOK_VERIFY_SIGNATURE_HEADER_VALUE}
      - UPLOAD_DIR=/usr/src/app/uploads
      - PUBLIC_DIR=/usr/src/app/public
      - PRIVATE_DIR=/usr/src/app/private
      - PORT=3000
    volumes:
      - type: bind
        source: ${MEDIA_STORAGE_PATH:-/var/lib/coolify/media_storage}
        target: /usr/src/app/uploads
      - type: bind
        source: ${SYSTEM_MEDIA_PATH:-/var/lib/coolify/system_media}
        target: /usr/src/app/public
      - type: bind
        source: ${PRIVATE_FILES_PATH:-/var/lib/coolify/private_files}
        target: /usr/src/app/private
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    networks:
      - coolify

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_BACKEND_URL: https://ticket.ebnez.com.br/backend
        NODE_ENV: production
        DISABLE_ESLINT_PLUGIN: "true"
        GENERATE_SOURCEMAP: "false"
        CI: "false"
        NODE_OPTIONS: "--max-old-space-size=2048"
    ports:
      - "34467:8080"
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=https://ticket.ebnez.com.br/backend
      - BACKEND_URL=http://backend:3000
      - BACKEND_PATH=/backend
      - BACKEND_PROTOCOL=https
      - BACKEND_HOST=ticket.ebnez.com.br
      - BACKEND_PORT=443
    volumes:
      - type: bind
        source: ${MEDIA_STORAGE_PATH:-/var/lib/coolify/media_storage}
        target: /usr/src/app/uploads
        read_only: true
      - type: bind
        source: ${SYSTEM_MEDIA_PATH:-/var/lib/coolify/system_media}
        target: /usr/src/app/public
        read_only: true
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 1GB
        reservations:
          memory: 512MB
    networks:
      - coolify

networks:
  coolify:
    external: true

volumes:
  media_storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${MEDIA_STORAGE_PATH:-/var/lib/coolify/media_storage}
  system_media:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${SYSTEM_MEDIA_PATH:-/var/lib/coolify/system_media}
  private_files:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PRIVATE_FILES_PATH:-/var/lib/coolify/private_files}
